### ISSUE TITLE
Does not run on 1.8.9

### ISSUE THREAD

**Issue by kreezxil** [Techern/Melon-block-drops#1]
crash report:
https://gist.github.com/e65c0fc1d1cd712dd90b

fml server latest:
https://gist.github.com/52e9e1815bb7d5ef77b1

**Comment by CruzBishop** [comment]
Thanks, I'll try to get this done today :)

**Comment by CruzBishop** [comment]
This should work with version 1.2 :)

Thank you for your service again, @kreezxil!

(File has been uploaded, should be approved in an hour or so)

**Comment by kreezxil** [comment]
It is still crashing a dedicated server.

Issue: melon block crashes dedicated forge 1.8.9 b1764 server on startup while complaining about a nosuchfield error

crash report:
https://gist.github.com/7a83fd223ae0715bff92

fml server latest:
https://gist.github.com/ad638dedf9921db9ce43
