### ISSUE TITLE
https://github.com/Techern/Melon-block-drops/issues/1

### ISSUE THREAD

**Issue by kreezxil** [Techern/Melon-block-drops#3]
I thought github allowed us to reopen issues. Anyways it is still doing it.

these maybe a repost if issue #1 is not reopened.

Issue: melon block crashes dedicated forge 1.8.9 b1764 server on startup while complaining about a nosuchfield error

crash report:
https://gist.github.com/7a83fd223ae0715bff92

fml server latest:
https://gist.github.com/ad638dedf9921db9ce43

**Comment by CruzBishop** [comment]
Ugh, this error again. It used to drive me mad since it worked in a development environment but not in production.

I'll have a go at fixing it tonight, sorry :(

**Comment by 7934345** [comment]
I got the same error

[15:42:56] [Server thread/INFO] [SpawnerCraft]: SpawnerCraft init finished
[15:42:56] [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
[15:42:56] [Server thread/ERROR] [FML]:
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHE    MelonBlockDrop{1.2.0} [Melon Block Drop](MelonBlockDrop-1.2.0.jar)
[15:42:57] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[15:42:57] [Server thread/ERROR] [FML]: Caught exception from MelonBlockDrop
java.lang.NoSuchFieldError: melon_block

**Comment by CruzBishop** [comment]
Ok, it looks like something broke and obfuscation never occurred?

Strange.

I've just set an upload for 1.2.1, **hopefully** it will work now :)

(please let it work now)

**Comment by CruzBishop** [comment]
Just examined it manually, seems to be working with 1.2.1 - Just waiting for approval from a reviewer :+1:

**Comment by kreezxil** [comment]
You could also issue released on Github too, then we wouldn't have to wait on a Curse reviewer.

-----Original Message-----

**Comment by CruzBishop** [comment]
@kreezxil Yeah :( I didn't think of that

Looks like it was approved overnight, hopefully it will work now :)

I'll keep this one open for another day or two in case it occurs again, but hopefully there'll be no issues

**Comment by kreezxil** [comment]
I did get it btw and or is not crashing.

-----Original Message-----

**Comment by CruzBishop** [comment]
That's great :) I'll close this now and hope it keeps working. Thanks, @kreezxil and @7934345
